### ISSUE TITLE
Failed step "analyzeCommits" 

### ISSUE THREAD

**Issue by timneedham** [effervescentia/iolaus#8]
Hi,

Great idea for a tool! :smile:
I understand it's early days... but just hit this, and not quite sure what to do:

```
[iolaus] › ✖  error     Failed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[iolaus] › ✖  error     Failed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
{ TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/home/tim/repos/monorepo-experiments/node_modules/resolve-from/index.js:18:9)
    at module.exports (/home/tim/repos/monorepo-experiments/node_modules/resolve-from/index.js:52:47)
    at module.exports (/home/tim/repos/monorepo-experiments/node_modules/import-from/index.js:4:55)
    at module.exports (/home/tim/repos/monorepo-experiments/node_modules/@semantic-release/commit-analyzer/lib/load-parser-config.js:24:60)
    at analyzeCommits (/home/tim/repos/monorepo-experiments/node_modules/@semantic-release/commit-analyzer/index.js:29:24)
    at validator (/home/tim/repos/monorepo-experiments/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at pReduce (/home/tim/repos/monorepo-experiments/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at next (/home/tim/repos/monorepo-experiments/node_modules/p-reduce/index.js:17:9)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '@semantic-release/commit-analyzer' }
```

So I've added some `console.log()` statements to try and see what's going on, somehow these are the values being passed to `resolveFrom(fromDirectory, moduleId, silent)`:

* fromDirectory:** `"/home/tim/repos/capsulenairobi/monorepo-experiments"`
* moduleId:** `{"iolausrc":{"dryRun":true}}`
* **silent:** `undefined`

...so yeah, failing as `moduleId` is expected to be a string, and it's getting the config object.

Any thoughts? :-)
Any help gratefully received, happy to write-up any docs that I've needed to get things running - this project deserves to be a success as it's so very needed!

**Comment by timneedham** [comment]
...it's something to do with using a config file? Because `iolaus -d` completes successfully.

**Comment by timneedham** [comment]
Now getting...

`[iolaus] [@semantic-release/commit-analyzer] › Analysis of 0 commits complete: no release`

Should each repo in `/packages` be its own GitHub repo (because that would be even better if that's the case!)

**Comment by timneedham** [comment]
So I've made everything in `/packages` its own GitHub repo, each with an initial release, all at `v1.0.0`, but it's still not picking-up either commits of the monorepo, or changes in the packages:

```
[iolaus] › ✔  success   Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[iolaus] › ✔  success   Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[iolaus] › No git tag version found
[iolaus] › No previous release found, retrieving all commits
[iolaus] › Found 10 commits since last release
[iolaus] › ☒  complete  packages verified
[iolaus] › Verify authentication for registry https://registry.npmjs.org/
[iolaus] › …  awaiting  looking for updates
[iolaus] › Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[iolaus] › Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[iolaus] [@semantic-release/commit-analyzer] › Analysis of 0 commits complete: no release
[iolaus] [@semantic-release/commit-analyzer] › Analysis of 0 commits complete: no release
[iolaus] › ✔  success   Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[iolaus] › ✔  success   Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[iolaus] › ⚠  warning   no releases found, exiting now
```

Any thoughts what I'm doing wrong?

**Comment by effervescentia** [comment]
@timneedham I'm sorry for taking so long to get back to you!
I had honestly just gotten this to a place where I was finally able to use it to ship another project that required this sort of multi-release system to exist.

I _have_ encountered your initial error, it appears to only appear when providing a `.iolausrc` config file instead of using the CLI options. For now I'll add an addendum to the `README.md` while I try to resolve [the issue](https://github.com/effervescentia/iolaus/issues/9) (quickly, as I would prefer to be using a config file myself 😛).

As for the second part, I believe that there's a good chance I haven't actually accounted for the case where there are no initial commits since in my case I already had a number of conventional commits in my repo from previous attempts at releases systems 😄. I will also add [this as a feature](https://github.com/effervescentia/iolaus/issues/10) shortly, as I don't expect it will be difficult. 

Just in case there are any other issues affecting your repo, you can also try running these troubleshooting steps (I'll add some additional details to the `README.md` as well):

- make sure that `lerna` has discovered your packages correctly by running `lerna list`, if you don't see any packages then you may have to specify their locations correctly in your `lerna.json` config file, or you may have to change the dependency versions to make sure that they match the versions in the relevant `package.json` files in your repo
- make sure that if you're using `commitizen` and the `cz-lerna-changelog` plugin for future commits that you want to trigger releases

> Now getting...
> 
> `[iolaus] [@semantic-release/commit-analyzer] › Analysis of 0 commits complete: no release`
> 
> Should each repo in `/packages` be its own GitHub repo (because that would be even better if that's the case!)

The packages don't each need to be individual github repositories, currently the release behaviour expects them to all be in one monorepo, as it currently generates [scoped tag names](https://github.com/effervescentia/iolaus/tags) based on the package names and a [single changelog](https://github.com/effervescentia/iolaus/blob/master/CHANGELOG.md) to describe them all. However I'd be happy to add a feature to support git submodules or subtrees if you'd be able to help me better scope it to fit with those workflows.

**Comment by effervescentia** [comment]
@timneedham just ran a test locally to see if you could kickstart the release process yourself while I'm still getting those features ready. I found that if you use `commitizen` to create an initial release (again using that [`cz-lerna-changelog`](https://www.npmjs.com/package/cz-lerna-changelog) plugin) and select either `fix` or `feat` in order to have the commit analyzer recognise that a release is required. In the last step select all of the packages that are listed. Running a release at this point should then create all the `v1.0.0` tags and do a `1.0.0` release on `npm`.

**Comment by effervescentia** [comment]
@timneedham with the [latest release](https://www.npmjs.com/package/iolaus/v/1.5.0) (`v1.5.0`) I've added support for a `--initial` flag that can be passed to `iolaus` to force a `v1.0.0` release of any package that would not otherwise be released based on an analysis of the commit history.

**Comment by effervescentia** [comment]
Just created another release `v1.5.1` to fix the bug preventing a configuration file being used to provide options for `iolaus`. Hopefully this should be sufficient to get you back in working order, but I'll leave this issue open for a bit if you still need any help setting it up for your project.
